18章 Ruby落葉拾い
* 18.2 環境変数
  rubyの実行に影響を与える環境変数
  - PATH
    いわずとしれたコマンドを探索するために使用される。
    rubyでは ``(バッククオート)によるコマンドの実行に影響する
    -S にも影響する。
   - RUBYLIB
     RUBYLIBの値は$LOAD_PATH に実行時に追加してくれる
     $LOAD_PATHは require や load の際の検索場所になる。
     - 個人的な設定
       RUBYLIB="lib"
       # 1.9なら .(カレントディレクトリ)を含めるのもありかも。
   - RUBYOPT
     rubyを起動する際のデフォルトオプションを指定できる。
     RUBYOPT="-Ku" とかいれてるときもありました。
     -wなんかもよいかも。
   - HOME
     引数なしのDir.chdirの移動先
   - LOG_DIR
     HOMEが未設定の場合に参照される
   - RUBY_PATH
     -S を使用した際に PATH より優先して検索する場所
     windows環境で使ってる人がいるとかきいたことがあるような気がする。
* 18.3 リテラル
  リテラルとはオブジェクトの文字列表現。
  その文字を評価するとなんらかのRubyオブジェクトになる。
  例えば
  "abc" -> 評価すると abc という文字列オブジェクトを返す
  `コマンド` -> 評価すると コマンドの実行結果の文字列オブジェクトを返す
  数値、文字列、配列、ハッシュ、正規表現
* 18.4 組み込み変数
  先頭に $ がつく。

  - $LOAD_PATH, $:
    requireが.rbファイルを検索する場所
    失敗する場合は確認してみよう。動的に追加も可能。

   - $! $@
     $! 例外の内容
     $@ 例外の場所
     直接使う機会はいまだにないなあ。

   - $KCODE
     1.8まで 漢字コードの指定
     u -> UTF-8
     s -> Shift-JIS
     e -> EUC
     -Kで指定できるやつ

   - $SAFE
     セキュリティレベルの設定につかう。
     セキュリティレベルがたかくなると危険なコードは実行できなくなる。
     ユーザからの入力をevalしたりだとかができなくなる。

   - $> $< $stdout $stdin
     標準出力 標準入力
     リダイレクトを思いうかべればわからなくならない。
* 18.5 組み込み定数
  全部大文字。変数との違いは設定の用途には使えない。
  実行した開始したら変更のない値と考えることができそう。
  STDIN STDOUT -> $stdoutなどは再代入で pやputsの動作をかえることができる
* 18.6 疑似変数
  selfとかnilとかfalseとかtrueとか リテラルでもキーワードでもないらしい。
* 18.7 BEGIN{} END{}
  awk由来だっけな。
  開始直後と実行終了後の手続を記述できる。
  ENDは sinatra でrackを使わない場合のブート方法として使われてた。
* 18.8 aliasとundef
  - alias 別名 元の名前
    メソッドに別名をつけることができる。
    メソッドを一時的におきかえたりするのに使う。
   - undef
     メソッドを未定義にできる。
     使ったことないっす。
* 18.9 多重代入
  [[file:18-9-multi.rb]]
* 18.10ローカル変数
  Rubyには4種類のローカル変数のスコープがある。
  - クラス
   - モジュール(クラスとほぼ一緒)
   - メソッド定義
   - ファイル
     詳しくはメタプログラミング Rubyを。
     [[file:18-10-local.rb]]
* 18.11 エンコーディング
  1.9からは ソースコード 文字列オブジェクト IO 正規表現が
  それぞれが別々のエンコーディングをもつことができるようになった。
  ソースコードのエンコードを指定するにはファイルの先頭に

  # coding: utf-8 -*-

  を記述。
  emacsの記述にあわせて以下のようにかかれていることも多い
  # -*- coding: utf-8 -*-
